# Generated by Django 4.2.2 on 2024-05-18 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_message_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('id',), 'permissions': [('can_view_messages', 'can view messages')], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
