# Generated by Django 5.0.4 on 2024-04-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_mailing_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempt',
            name='date_last_send',
        ),
        migrations.AddField(
            model_name='attempt',
            name='answer_server',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ сервера'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='date_send',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата отправки'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
    ]
