# Generated by Django 4.2.2 on 2024-05-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_alter_mailing_options_alter_mailing_mailing_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Заголовок'),
        ),
    ]
