# Generated by Django 4.2.2 on 2024-05-18 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_message_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailing', '0008_log_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='message.message', verbose_name='Сообщение'),
        ),
    ]
