# Generated by Django 4.2.2 on 2024-05-18 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0009_alter_log_owner_alter_mailing_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ('id',), 'permissions': [('can_view_logs', 'can view logs')], 'verbose_name': 'Лог', 'verbose_name_plural': 'Логи'},
        ),
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ('id',), 'permissions': [('can_view_mailings', 'can view mailings'), ('can_check_status_mailings', 'can check status mailings')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
