# Generated by Django 5.0.4 on 2024-04-06 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('commentary', models.TextField(verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Клиента',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_first_send', models.DateTimeField(verbose_name='Дата первой отправки')),
                ('periodicity', models.CharField(blank=True, choices=[('D', 'Раз в день'), ('W', 'Раз в неделю'), ('M', 'Раз в месяц')], max_length=1, null=True, verbose_name='Периодичность')),
                ('mailing_status', models.CharField(blank=True, choices=[('C', 'Создана'), ('R', 'Запущена'), ('S', 'Остановлена'), ('E', 'Завершена')], max_length=1, null=True, verbose_name='Статус')),
                ('client', models.ManyToManyField(to='client.client', verbose_name='Клиент')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.message', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Рассылку',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_last_send', models.DateTimeField(verbose_name='Дата последней отправки')),
                ('attempt_status', models.CharField(blank=True, choices=[('Y', 'Успешно'), ('N', 'Не успешно')], max_length=1, null=True, verbose_name='Статус')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client', verbose_name='Клиент')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.mailing', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Попытку',
                'verbose_name_plural': 'Попытки',
            },
        ),
    ]
