# Generated by Django 5.0.4 on 2024-04-07 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_rename_commentary_client_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='client',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='message',
        ),
        migrations.DeleteModel(
            name='Attempt',
        ),
        migrations.DeleteModel(
            name='Mailing',
        ),
    ]
