# Generated by Django 4.2.2 on 2024-05-18 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_client_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('id',), 'permissions': [('can_view_clients', 'can view clients')], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
    ]
