# Generated by Django 4.2.2 on 2024-05-19 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('id',), 'verbose_name': 'Блог', 'verbose_name_plural': 'Блоги'},
        ),
    ]
